aws_security_group = "${var.AWS_SECURITY_GROUP}"
aws_subnet_ids = "${split(",", var.AWS_SUBNET_IDS)}"
aws_vpc_id = "${var.AWS_VPC_ID}"
aws_tf_bucket = "${var.AWS_TF_BUCKET}"
aws_ssl_certificate_arn = "${var.AWS_SSL_CERTIFICATE_ARN}"
aws_route53_zone_id = "${var.AWS_ROUTE53_ZONE_ID}"
aws_domain = "${var.AWS_DOMAIN}"
aws_subdomain = "${var.AWS_SUBDOMAIN}"