pipeline {
    agent any

    environment {
        GITHUB_TOKEN = credentials('GITHUB_TOKEN')
    }

    stages {
        stage('Check Token') {
            steps {
                script {
                    sh 'echo "GitHub Token: $GITHUB_TOKEN"'
                }
            }
        }
    }
}
